apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/nissimuseri/demo-app
  newTag: 9b90763444350f7a9e55223abd13e4f4abe1211cd58e8e13c6f61c3a08cb975f